# Generated by Django 6.0.4 on 2026-05-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_farm"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="crop_condition",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="farm",
            name="fertilizer_used",
            field=models.CharField(default="None", max_length=255),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="filter_type",
            field=models.CharField(default="None", max_length=255),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="leakage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="pump_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="water_source",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
