# Generated by Django 6.0.4 on 2026-05-12 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_farm_crop_condition_farm_fertilizer_used_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("equipment_name", models.CharField(max_length=255)),
                ("maintenance_type", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
