# Generated by Django 6.0.4 on 2026-05-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_maintenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="crop",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
